### ISSUE TITLE
Diagram-js for Entitiy Modeling

### ISSUE THREAD

**Issue by lixaotec** [bpmn-io/diagram-js#273]
Dear Friends,

Just wondering if is it possible to use diagram-js for building a Entity Relations Modeling? Would that be a hard task to do with it?
Can you people suggest me starting point?
I´ve tried draw.io tool with mxGraph, despite their usability, its too hard to fork a new tool, and found it to be slow, as for a bunch of hundred entities, the tool got too slow.

Appreciate any help or sugestion.

### Steps to reproduce the Behavior

**Comment by nikku** [comment]
It is possible to build a ER diagram editor for sure, the question is how much time and resources you'd like to invest. Due to the nature of diagram-js there is quite some stuff you'd need to build on top, depending on the feature set you'd like to support. 

Take a look at [bpmn-js](https://github.com/bpmn-io/bpmn-js), [cmmn-js](https://github.com/bpmn-io/cmmn-js) and [dmn-js-drd](https://github.com/bpmn-io/dmn-js/tree/master/packages/dmn-js-drd). All these libraries implement editors on top of the diagram-js core (dmn-js-drd being the most simple one).

**Comment by lixaotec** [comment]
Dear fellow @nikku , 

I know this might be an old subject, however im back with the idea of building a 'class' modeler, and Im evaluating the easiest and narrow  lib / method for constructing such tool.

Im still not sure if would be eaiser to use this tool (diagram-js) or trying D3 library, However i need the connections between elements, and your approch seem to be straigth as it is ready.

What would you suggest me please? Other libs / approach perhaps?

Thanks
