### ISSUE TITLE
Add code coverage shield to readme

### ISSUE THREAD

**Issue by poteat** [bpmn-io/diagram-js#315]
Let's let everyone see our commitment to code quality!  A simple fix :+1:

**Comment by pinussilvestrus** [comment]
Hi @poteat,
Thanks first for your contribution! We always appreciate external contributions in our projects 💪

We just finished a discussion whether we want to add the [codecov badge](https://codecov.io/) in all of our projects. We came to the conclusion that we _won't_. In our opinion, the coverage badge does not reflect the overall quality of our code (as you mentioned in #314) and especially of our tests.  One of our main goals is to write _good tests_, and not as many as possible. We don't want to force a 100% code quality. Adding this kind of badges does not reflect our view of having a good test suite. CodeCov offers a great tool for us inside our review process to assure new features and fixed bugs are always covered by certain tests. Instead of outline our coverage percentage, we concentrate on increasing it (a point we are always open for contribution as well!). 

I'll close this pull request since we are not going to add the badge. However, thanks again! Feel free to continue sharing great contributions 👍If you have another thought regarding this topic; we are open to chat.

Regards,
Niklas
