### ISSUE TITLE
Karma tests failed in Chrome Headless

### ISSUE THREAD

**Issue by FrankiePo** [bpmn-io/diagram-js#485]
__Describe the Bug__

Tests failed in Chrome Headless with following error.

```
Chrome Headless 85.0.4182.0 (Windows 10) features/move - MovePreview markers should clone markers FAILED
        AssertionError: expected 'url("#marker-start-clone")' to deeply equal 'url(#marker-start-clone)'
            at eval (webpack-internal:///./test/spec/features/move/MovePreviewSpec.js:601:56)
            at Diagram.invoke (webpack-internal:///./node_modules/didi/dist/index.esm.js:196:20)
            at Context.eval (webpack-internal:///./test/helper/index.js:132:23)
Chrome Headless 85.0.4182.0 (Windows 10): Executed 1593 of 1598 (1 FAILED) (skipped 5) (17.37 secs / 11.666 secs)
TOTAL: 1 FAILED, 1592 SUCCESS
```
__Steps to Reproduce__

1. Run tests in ChromeHeadless `TEST_BROWSERS=ChromeHeadless npm run test`

__Expected Behavior__

All tests succeed

__Environment__

Please complete the following information:

 - Browser: Chrome Headless 85.0.4182.0
 - OS: Windows 10
 - Library version: develop

**Comment by MaxTru** [comment]
The failing test case tests the preview feature, but the actual issue why it fails, is how Chrome behaves when doing `element.style["marker-end"] = "url(#marker-end)"` 

In tiny-svg we set the style as `element.style["marker-end"] = "url(#marker-end)"` (see [here](https://github.com/bpmn-io/tiny-svg/blob/master/lib/attr.js#L91)). When doing this in Chrome, the resulting element will look like this 
```html
<div id="testDiv" style="marker-end: url("#marker-end");>Hello</div>
```

This is valid usage of `url()` (see [W3C](https://www.w3.org/TR/CSS2/syndata.html#uri)), however in `diagram-js` we assume in multiple places to not include the `"`-marks (see https://github.com/bpmn-io/diagram-js/blob/develop/test/spec/features/move/renderer/MarkerRenderer.js#L124, https://github.com/bpmn-io/diagram-js/blob/develop/test/spec/features/move/MovePreviewSpec.js#L647, https://github.com/bpmn-io/diagram-js/blob/develop/lib/features/preview-support/PreviewSupport.js#L234, https://github.com/bpmn-io/diagram-js/blob/develop/lib/features/grid-snapping/visuals/Grid.js#L85)

I see two solution options:
**A) Relax the tests**
Since `url("#marker-end")` and `url(#marker-end)` are both valid and carry same semantics, we could just relax the tests.

**B) Always set to `url("#marker-end")`**
In https://github.com/bpmn-io/tiny-svg/blob/master/lib/attr.js#L91 we could enforce using `"` encapsulating the `value`, to always have the exact same behavior on all environments. (This is more work of course then A))

Will discuss with the team and then decide

-----------
Example html:
```html
<div id="testDiv">Hello</div>
<script>
document.getElementById("testDiv").style["marker-end"] = "url(#marker-end)";
</script>

```
(See example.html)

**Comment by MaxTru** [comment]
Fixed using option **A)**
