### ISSUE TITLE
Viewer How to collapse or expand subprocesses？

### ISSUE THREAD

**Issue by tony2y** [bpmn-io/diagram-js#848]
### Describe the Question

```
import ModelingModule from "diagram-js/lib/features/modeling";
import BpmnViewer from "bpmn-js/lib/Viewer";

// init
this.bpmnViewer = new BpmnViewer({
            container: this.$refs.flowCanvas,
            height: 'calc(100vh - 200px)',
            additionalModules:[
              ZoomScrollModule,
              MoveCanvasModule,
              ModelingModule
            ],
          });
       
// click event
 const eventBus = bpmnViewer.get('eventBus');
      const canvas = bpmnViewer.get('canvas');
      eventBus.on('element.click', (e) => {
        if (e.element.type === "bpmn:SubProcess") {
          const modeling = bpmnViewer.get("modeling");
          const element = e.element;
          modeling.toggleCollapse(element);

        }
      });
```
 use  modeling.toggleCollapse(element) is invalid;
<img width="490" alt="image" src="https://github.com/bpmn-io/diagram-js/assets/38598582/75a8eb60-3154-4257-9786-177d85ffbea2">

 
### Desired result
 Subprocesses can be collapsed or expanded normally in Viewer

**Comment by tony2y** [comment]
@nikku

**Comment by nikku** [comment]
@tony2y I'm not sure what you'd like to accomplish:

* In the viewer you can drilldown (jump into) collapsed sub-processes
* In the viewer you can view expanded sub-processes
* In the viewer **you cannot** change a collapsed sub-process to an expanded sub-process (and vice versa), because **that is a modeling operation**

If the later is what you're asking for then this is *won't fix* for us.
